In [1]:
import pandas as pd 
import numpy as np

#df = pd.read_excel("WWCUP.xlsx")
#df = pd.read_excel("Laligafinal.xlsx")

#df = pd.read_excel("EPL.xlsx")
#df = pd.read_excel("FAWSL.xlsx")
#df = pd.read_excel("FWCUP.xlsx")

#df = pd.read_excel("ISL.xlsx")
#df = pd.read_excel("NWSL.xlsx")
#df = pd.read_excel("UCLfinal.xlsx")


#df = pd.read_excel("UEURO.xlsx")
df = pd.read_excel("UWEURO.xlsx")




print(df.shape)
print(df.columns)

(876, 30)
Index(['Unnamed: 0', 'id', 'index', 'period', 'timestamp', 'minute', 'second',
       'possession', 'possession_team_name', 'player_id', 'player_name',
       'duration', 'under_pressure', 'play_pattern_name', 'shot_freeze_frame',
       'shot_type_name', 'shot_technique_name', 'shot_outcome_name',
       'shot_body_part_name', 'shot_statsbomb_xg', 'previous_type_name',
       'previous_pass_height_name', 'location_x', 'location_y',
       'shot_end_location_x', 'shot_end_location_y', 'match_id',
       'home_team_home_team_name', 'away_team_away_team_name', 'home_away'],
      dtype='object')

In [2]:
import ast

for i in range(0, df.shape[0]-1):
    try:
        df['shot_freeze_frame'].iloc[i] = ast.literal_eval(df['shot_freeze_frame'].iloc[i])
    except:
        None

/Users/aritramajumdar/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [3]:
def dict_to_dataframe(a):
    dataframe = df[a].apply(pd.Series)
    dataframe.columns = [str(a) + "_" + str(col) for col in dataframe.columns]
    return dataframe

df_sff = dict_to_dataframe('shot_freeze_frame')
print(df_sff.shape)

(876, 20)

In [4]:
df_sff.head()

,shot_freeze_frame_0,shot_freeze_frame_1,shot_freeze_frame_2,shot_freeze_frame_3,shot_freeze_frame_4,shot_freeze_frame_5,shot_freeze_frame_6,shot_freeze_frame_7,shot_freeze_frame_8,shot_freeze_frame_9,shot_freeze_frame_10,shot_freeze_frame_11,shot_freeze_frame_12,shot_freeze_frame_13,shot_freeze_frame_14,shot_freeze_frame_15,shot_freeze_frame_16,shot_freeze_frame_17,shot_freeze_frame_18,shot_freeze_frame_19
0,"{'location': [107.6, 39.1], 'player': {'id': 1...","{'location': [91.8, 16.0], 'player': {'id': 15...","{'location': [98.1, 25.2], 'player': {'id': 46...","{'location': [118.6, 42.6], 'player': {'id': 1...","{'location': [107.8, 40.4], 'player': {'id': 3...","{'location': [102.7, 34.2], 'player': {'id': 1...","{'location': [103.4, 28.7], 'player': {'id': 1...","{'location': [113.7, 45.2], 'player': {'id': 2...","{'location': [103.8, 21.5], 'player': {'id': 2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"{'location': [93.6, 64.6], 'player': {'id': 15...","{'location': [98.6, 53.8], 'player': {'id': 46...","{'location': [104.8, 41.2], 'player': {'id': 4...","{'location': [107.3, 45.7], 'player': {'id': 4...","{'location': [110.2, 41.8], 'player': {'id': 4...","{'location': [112.6, 39.0], 'player': {'id': 1...","{'location': [111.2, 51.4], 'player': {'id': 1...","{'location': [111.3, 56.0], 'player': {'id': 5...","{'location': [118.3, 39.9], 'player': {'id': 3...","{'location': [91.6, 64.6], 'player': {'id': 25...","{'location': [107.1, 34.8], 'player': {'id': 4...","{'location': [114.4, 36.3], 'player': {'id': 2...","{'location': [111.2, 46.2], 'player': {'id': 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"{'location': [119.3, 38.7], 'player': {'id': 3...","{'location': [96.8, 30.0], 'player': {'id': 15...","{'location': [94.3, 37.1], 'player': {'id': 46...","{'location': [101.2, 34.6], 'player': {'id': 1...","{'location': [101.3, 35.7], 'player': {'id': 4...","{'location': [100.5, 43.8], 'player': {'id': 1...","{'location': [101.4, 50.9], 'player': {'id': 5...","{'location': [94.0, 48.1], 'player': {'id': 46...","{'location': [85.5, 62.7], 'player': {'id': 15...","{'location': [81.8, 63.7], 'player': {'id': 10...","{'location': [101.8, 21.9], 'player': {'id': 3...","{'location': [100.4, 33.3], 'player': {'id': 4...","{'location': [97.6, 41.7], 'player': {'id': 25...","{'location': [99.3, 60.3], 'player': {'id': 10...",NaN,NaN,NaN,NaN,NaN,NaN
3,"{'location': [111.9, 11.9], 'player': {'id': 1...","{'location': [110.3, 27.3], 'player': {'id': 1...","{'location': [118.4, 39.1], 'player': {'id': 1...","{'location': [114.8, 39.7], 'player': {'id': 1...","{'location': [112.7, 39.4], 'player': {'id': 2...","{'location': [110.9, 46.2], 'player': {'id': 2...","{'location': [112.7, 43.9], 'player': {'id': 2...","{'location': [111.0, 51.0], 'player': {'id': 2...","{'location': [105.0, 57.2], 'player': {'id': 3...","{'location': [106.1, 42.8], 'player': {'id': 4...","{'location': [106.3, 48.4], 'player': {'id': 1...","{'location': [101.7, 47.3], 'player': {'id': 1...","{'location': [103.8, 60.0], 'player': {'id': 1...","{'location': [111.6, 39.8], 'player': {'id': 4...","{'location': [110.9, 41.3], 'player': {'id': 5...","{'location': [108.4, 38.9], 'player': {'id': 1...","{'location': [111.7, 45.4], 'player': {'id': 1...","{'location': [93.9, 24.2], 'player': {'id': 46...","{'location': [113.6, 38.4], 'player': {'id': 1...",NaN
4,"{'location': [113.2, 41.4], 'player': {'id': 5...","{'location': [116.0, 42.6], 'player': {'id': 1...","{'location': [112.5, 39.0], 'player': {'id': 1...","{'location': [112.7, 45.9], 'player': {'id': 4...","{'location': [115.5, 37.4], 'player': {'id': 1...","{'location': [96.2, 28.4], 'player': {'id': 46...","{'location': [112.8, 46.4], 'player': {'id': 3...","{'location': [114.9, 44.3], 'player': {'id': 1...","{'location': [112.0, 28.5], 'player': {'id': 2...","{'location': [118.3, 38.4], 'player': {'id': 2...","{'location': [117.8, 39.7], 'player': {'id': 1...","{'location': [111.1, 38.7], 'player': {'id': 4...","{'location': [112.7, 44.7], 'player': {'id': 1...","{'location': [117.4, 43.7], 'player': {'id': 2...","{'location': [116.0, 41.4], 'player': {'id': 2...","{'location': [106.4, 44.7], 'player': {'id': 1...","{'location': [119.1, 39.9], 'player': {'id': 1...",NaN,NaN,NaN

In [5]:
df_sff.tail()

,shot_freeze_frame_0,shot_freeze_frame_1,shot_freeze_frame_2,shot_freeze_frame_3,shot_freeze_frame_4,shot_freeze_frame_5,shot_freeze_frame_6,shot_freeze_frame_7,shot_freeze_frame_8,shot_freeze_frame_9,shot_freeze_frame_10,shot_freeze_frame_11,shot_freeze_frame_12,shot_freeze_frame_13,shot_freeze_frame_14,shot_freeze_frame_15,shot_freeze_frame_16,shot_freeze_frame_17,shot_freeze_frame_18,shot_freeze_frame_19
871,"{'location': [101.8, 26.9], 'player': {'id': 1...","{'location': [103.0, 15.6], 'player': {'id': 4...","{'location': [97.5, 36.7], 'player': {'id': 10...","{'location': [96.1, 48.3], 'player': {'id': 10...","{'location': [103.6, 32.9], 'player': {'id': 3...","{'location': [93.0, 37.0], 'player': {'id': 31...","{'location': [96.4, 29.3], 'player': {'id': 46...","{'location': [106.1, 32.5], 'player': {'id': 1...","{'location': [102.9, 34.7], 'player': {'id': 1...","{'location': [100.2, 36.0], 'player': {'id': 4...","{'location': [102.7, 32.3], 'player': {'id': 4...","{'location': [106.1, 36.0], 'player': {'id': 1...","{'location': [106.0, 41.9], 'player': {'id': 5...","{'location': [117.9, 38.9], 'player': {'id': 3...",NaN,NaN,NaN,NaN,NaN,NaN
872,"{'location': [91.1, 44.7], 'player': {'id': 31...","{'location': [99.9, 34.7], 'player': {'id': 15...","{'location': [101.2, 58.2], 'player': {'id': 4...","{'location': [88.9, 58.8], 'player': {'id': 10...","{'location': [100.6, 56.5], 'player': {'id': 1...","{'location': [98.6, 48.1], 'player': {'id': 43...","{'location': [96.8, 32.5], 'player': {'id': 46...","{'location': [103.3, 39.6], 'player': {'id': 1...","{'location': [118.7, 41.6], 'player': {'id': 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
873,"{'location': [92.5, 30.1], 'player': {'id': 31...","{'location': [102.0, 39.6], 'player': {'id': 1...","{'location': [94.3, 23.0], 'player': {'id': 15...","{'location': [86.0, 33.5], 'player': {'id': 10...","{'location': [101.2, 48.7], 'player': {'id': 1...","{'location': [101.3, 42.5], 'player': {'id': 4...","{'location': [102.7, 39.1], 'player': {'id': 1...","{'location': [98.9, 26.9], 'player': {'id': 46...","{'location': [116.9, 41.5], 'player': {'id': 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
874,"{'location': [101.3, 41.4], 'player': {'id': 1...","{'location': [100.4, 25.9], 'player': {'id': 4...","{'location': [88.5, 43.4], 'player': {'id': 10...","{'location': [106.9, 62.2], 'player': {'id': 4...","{'location': [106.4, 44.6], 'player': {'id': 1...","{'location': [87.9, 59.5], 'player': {'id': 46...","{'location': [92.9, 29.7], 'player': {'id': 15...","{'location': [101.5, 47.5], 'player': {'id': 4...","{'location': [92.3, 47.3], 'player': {'id': 31...","{'location': [107.9, 55.0], 'player': {'id': 4...","{'location': [107.5, 44.4], 'player': {'id': 4...","{'location': [108.5, 37.2], 'player': {'id': 1...","{'location': [106.5, 47.0], 'player': {'id': 1...","{'location': [88.2, 57.9], 'player': {'id': 15...","{'location': [100.7, 54.2], 'player': {'id': 5...","{'location': [119.1, 42.0], 'player': {'id': 3...",NaN,NaN,NaN,NaN
875,"[{'location': [100.0, 29.2], 'player': {'id': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
from pandas import isnull
df_sff=df_sff.applymap(lambda x: {'location': [0, 0]} if isnull(x) else x)

In [7]:
def new_frame(col):
    new_items = []
    new_items1 = []
    for i in range(0, df.shape[0]):
        try:
            new_items.append(df_sff[col].values[i]['location'][0])
            new_items1.append(df_sff[col].values[i]['location'][1])
        except:
            0
    return new_items, new_items1

In [8]:
x0, y0 = new_frame('shot_freeze_frame_0')

df_sff['shot_freeze_frame_0_x'] = pd.DataFrame(x0)
df_sff['shot_freeze_frame_0_y'] = pd.DataFrame(y0)


x1, y1 = new_frame('shot_freeze_frame_1')

df_sff['shot_freeze_frame_1_x'] = pd.DataFrame(x1)
df_sff['shot_freeze_frame_1_y'] = pd.DataFrame(y1)


x2, y2 = new_frame('shot_freeze_frame_2')

df_sff['shot_freeze_frame_2_x'] = pd.DataFrame(x2)
df_sff['shot_freeze_frame_2_y'] = pd.DataFrame(y2)


x3, y3 = new_frame('shot_freeze_frame_3')

df_sff['shot_freeze_frame_3_x'] = pd.DataFrame(x3)
df_sff['shot_freeze_frame_3_y'] = pd.DataFrame(y3)


x4, y4 = new_frame('shot_freeze_frame_4')

df_sff['shot_freeze_frame_4_x'] = pd.DataFrame(x4)
df_sff['shot_freeze_frame_4_y'] = pd.DataFrame(y4)

x5, y5 = new_frame('shot_freeze_frame_5')

df_sff['shot_freeze_frame_5_x'] = pd.DataFrame(x5)
df_sff['shot_freeze_frame_5_y'] = pd.DataFrame(y5)


x6, y6 = new_frame('shot_freeze_frame_6')

df_sff['shot_freeze_frame_6_x'] = pd.DataFrame(x6)
df_sff['shot_freeze_frame_6_y'] = pd.DataFrame(y6)


x7, y7 = new_frame('shot_freeze_frame_7')

df_sff['shot_freeze_frame_7_x'] = pd.DataFrame(x7)
df_sff['shot_freeze_frame_7_y'] = pd.DataFrame(y7)

x8, y8 = new_frame('shot_freeze_frame_8')

df_sff['shot_freeze_frame_8_x'] = pd.DataFrame(x8)
df_sff['shot_freeze_frame_8_y'] = pd.DataFrame(y8)


x9, y9 = new_frame('shot_freeze_frame_9')

df_sff['shot_freeze_frame_9_x'] = pd.DataFrame(x9)
df_sff['shot_freeze_frame_9_y'] = pd.DataFrame(y9)

x10, y10 = new_frame('shot_freeze_frame_10')

df_sff['shot_freeze_frame_10_x'] = pd.DataFrame(x10)
df_sff['shot_freeze_frame_10_y'] = pd.DataFrame(y10)


x11, y11 = new_frame('shot_freeze_frame_11')

df_sff['shot_freeze_frame_11_x'] = pd.DataFrame(x11)
df_sff['shot_freeze_frame_11_y'] = pd.DataFrame(y11)


x12, y12 = new_frame('shot_freeze_frame_12')

df_sff['shot_freeze_frame_12_x'] = pd.DataFrame(x12)
df_sff['shot_freeze_frame_12_y'] = pd.DataFrame(y12)


x13, y13 = new_frame('shot_freeze_frame_13')

df_sff['shot_freeze_frame_13_x'] = pd.DataFrame(x13)
df_sff['shot_freeze_frame_13_y'] = pd.DataFrame(y13)


x14, y14 = new_frame('shot_freeze_frame_14')

df_sff['shot_freeze_frame_14_x'] = pd.DataFrame(x14)
df_sff['shot_freeze_frame_14_y'] = pd.DataFrame(y14)


x15, y15 = new_frame('shot_freeze_frame_15')

df_sff['shot_freeze_frame_15_x'] = pd.DataFrame(x15)
df_sff['shot_freeze_frame_15_y'] = pd.DataFrame(y15)


x16, y16 = new_frame('shot_freeze_frame_16')

df_sff['shot_freeze_frame_16_x'] = pd.DataFrame(x16)
df_sff['shot_freeze_frame_16_y'] = pd.DataFrame(y16)


x17, y17 = new_frame('shot_freeze_frame_17')

df_sff['shot_freeze_frame_17_x'] = pd.DataFrame(x17)
df_sff['shot_freeze_frame_17_y'] = pd.DataFrame(y17)


x18, y18 = new_frame('shot_freeze_frame_18')

df_sff['shot_freeze_frame_18_x'] = pd.DataFrame(x18)
df_sff['shot_freeze_frame_18_y'] = pd.DataFrame(y18)


x19, y19 = new_frame('shot_freeze_frame_19')

df_sff['shot_freeze_frame_19_x'] = pd.DataFrame(x19)
df_sff['shot_freeze_frame_19_y'] = pd.DataFrame(y19)

"""
x20, y20 = new_frame('shot_freeze_frame_20')

df_sff['shot_freeze_frame_20_x'] = pd.DataFrame(x20)
df_sff['shot_freeze_frame_20_y'] = pd.DataFrame(y20)
"""

"\nx20, y20 = new_frame('shot_freeze_frame_20')\n\ndf_sff['shot_freeze_frame_20_x'] = pd.DataFrame(x20)\ndf_sff['shot_freeze_frame_20_y'] = pd.DataFrame(y20)\n"

In [9]:
df_sff.shape

(876, 60)

In [10]:
df_sff

,shot_freeze_frame_0,shot_freeze_frame_1,shot_freeze_frame_2,shot_freeze_frame_3,shot_freeze_frame_4,shot_freeze_frame_5,shot_freeze_frame_6,shot_freeze_frame_7,shot_freeze_frame_8,shot_freeze_frame_9,...,shot_freeze_frame_15_x,shot_freeze_frame_15_y,shot_freeze_frame_16_x,shot_freeze_frame_16_y,shot_freeze_frame_17_x,shot_freeze_frame_17_y,shot_freeze_frame_18_x,shot_freeze_frame_18_y,shot_freeze_frame_19_x,shot_freeze_frame_19_y
0,"{'location': [107.6, 39.1], 'player': {'id': 1...","{'location': [91.8, 16.0], 'player': {'id': 15...","{'location': [98.1, 25.2], 'player': {'id': 46...","{'location': [118.6, 42.6], 'player': {'id': 1...","{'location': [107.8, 40.4], 'player': {'id': 3...","{'location': [102.7, 34.2], 'player': {'id': 1...","{'location': [103.4, 28.7], 'player': {'id': 1...","{'location': [113.7, 45.2], 'player': {'id': 2...","{'location': [103.8, 21.5], 'player': {'id': 2...","{'location': [0, 0]}",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,"{'location': [93.6, 64.6], 'player': {'id': 15...","{'location': [98.6, 53.8], 'player': {'id': 46...","{'location': [104.8, 41.2], 'player': {'id': 4...","{'location': [107.3, 45.7], 'player': {'id': 4...","{'location': [110.2, 41.8], 'player': {'id': 4...","{'location': [112.6, 39.0], 'player': {'id': 1...","{'location': [111.2, 51.4], 'player': {'id': 1...","{'location': [111.3, 56.0], 'player': {'id': 5...","{'location': [118.3, 39.9], 'player': {'id': 3...","{'location': [91.6, 64.6], 'player': {'id': 25...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,"{'location': [119.3, 38.7], 'player': {'id': 3...","{'location': [96.8, 30.0], 'player': {'id': 15...","{'location': [94.3, 37.1], 'player': {'id': 46...","{'location': [101.2, 34.6], 'player': {'id': 1...","{'location': [101.3, 35.7], 'player': {'id': 4...","{'location': [100.5, 43.8], 'player': {'id': 1...","{'location': [101.4, 50.9], 'player': {'id': 5...","{'location': [94.0, 48.1], 'player': {'id': 46...","{'location': [85.5, 62.7], 'player': {'id': 15...","{'location': [81.8, 63.7], 'player': {'id': 10...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,"{'location': [111.9, 11.9], 'player': {'id': 1...","{'location': [110.3, 27.3], 'player': {'id': 1...","{'location': [118.4, 39.1], 'player': {'id': 1...","{'location': [114.8, 39.7], 'player': {'id': 1...","{'location': [112.7, 39.4], 'player': {'id': 2...","{'location': [110.9, 46.2], 'player': {'id': 2...","{'location': [112.7, 43.9], 'player': {'id': 2...","{'location': [111.0, 51.0], 'player': {'id': 2...","{'location': [105.0, 57.2], 'player': {'id': 3...","{'location': [106.1, 42.8], 'player': {'id': 4...",...,108.4,38.9,111.7,45.4,93.9,24.2,113.6,38.4,0.0,0.0
4,"{'location': [113.2, 41.4], 'player': {'id': 5...","{'location': [116.0, 42.6], 'player': {'id': 1...","{'location': [112.5, 39.0], 'player': {'id': 1...","{'location': [112.7, 45.9], 'player': {'id': 4...","{'location': [115.5, 37.4], 'player': {'id': 1...","{'location': [96.2, 28.4], 'player': {'id': 46...","{'location': [112.8, 46.4], 'player': {'id': 3...","{'location': [114.9, 44.3], 'player': {'id': 1...","{'location': [112.0, 28.5], 'player': {'id': 2...","{'location': [118.3, 38.4], 'player': {'id': 2...",...,106.4,44.7,119.1,39.9,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,"{'location': [101.8, 26.9], 'player': {'id': 1...","{'location': [103.0, 15.6], 'player': {'id': 4...","{'location': [97.5, 36.7], 'player': {'id': 10...","{'location': [96.1, 48.3], 'player': {'id': 10...","{'location': [103.6, 32.9], 'player': {'id': 3...","{'location': [93.0, 37.0], 'player': {'id': 31...","{'location': [96.4, 29.3], 'player': {'id': 46...","{'location': [106.1, 32.5], 'player': {'id': 1...","{'location': [102.9, 34.7], 'player': {'id': 1...","{'location': [100.2, 36.0], 'player': {'id': 4...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
872,"{'location': [91.1, 44.7], 'player': {'id': 31...","{'location': [99.9, 34.7], 'player': {'id': 15...","{'location': [101.2, 58.2], 'player': {'id': 4...","{'location': [88.9, 58.8], 'player': {'id': 10...","{'location': [100.6, 56.5], 'player': {'id': 1...","{'location': [98.6, 48.1], 'player': {'id': 43...","{'location': [96.8, 32.5], 'player': {'id': 46...","{'location': [103.3, 39.6], 'player': {'id': 1...","{'location': [118.7, 41.6], 'player': {'id': 1...","{'location': [0, 0]}",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
873,"{'location': [92.5, 30.1], 'player': {'id': 31...","{'location': [102.0, 39.6], 'player': {'id': 1...","{'location': [94.3, 23.0], 'player': {'id': 15...","{'location': [86.0, 33.5], 'player': {'id': 10...","{'location': [101.2, 48.7], 'player': {'id': 1...","{'location': [101.3, 42.5], 'player': {'id': 4...","{'location': [102.7, 39.1], 'player': {'id': 1...","{'location': [98.9, 26.9], 'player': {'id': 46...","{'location': [116.9, 41.5], 'player': {'id': 1...","{'location': [0, 0]}",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
874,"{'location': [101.3, 41.4], 'player': {'id': 1...","{'location': [100.4, 25.9], 'player': {'id': 4...","{'location': [88.5, 43.4], 'player': {'id': 10...","{'location': [106.9, 62.2], 'player': {'id': 4...","{'location': [106.4, 44.6], 'player': {'id': 1...","{'location': [87.9, 59.5], 'player': {'id': 46...","{'location': [92.9, 29.7], 'player': {'id': 15...","{'location': [101.5, 47.5], 'player': {'id': 4...","{'location': [92.3, 47.3], 'player': {'id': 31...","{'location': [107.9, 55.0], 'player': {'id': 4...",...,119.1,42.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
875,"[{'location': [100.0, 29.2], 'player': {'id': ...","{'location': [0, 0]}","{'location': [0, 0]}","{'location': [0, 0]}","{'location': [0, 0]}","{'location': [0, 0]}","{'location': [0, 0]}","{'location': [0, 0]}","{'location': [0, 0]}","{'location': [0, 0]}",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
a = ['shot_freeze_frame_0', 'shot_freeze_frame_1', 'shot_freeze_frame_2',
       'shot_freeze_frame_3', 'shot_freeze_frame_4', 'shot_freeze_frame_5',
       'shot_freeze_frame_6', 'shot_freeze_frame_7', 'shot_freeze_frame_8',
       'shot_freeze_frame_9', 'shot_freeze_frame_10', 'shot_freeze_frame_11',
       'shot_freeze_frame_12', 'shot_freeze_frame_13', 'shot_freeze_frame_14',
       'shot_freeze_frame_15', 'shot_freeze_frame_16', 'shot_freeze_frame_17',
       'shot_freeze_frame_18', 'shot_freeze_frame_19']

df_sff.drop(a, axis = 1, inplace = True)
print(df_sff.shape)
df = pd.concat([df, df_sff], axis = 1)
print(df.shape)

(876, 40)
(876, 70)

In [12]:
df.head()

,Unnamed: 0,id,index,period,timestamp,minute,second,possession,possession_team_name,player_id,...,shot_freeze_frame_15_x,shot_freeze_frame_15_y,shot_freeze_frame_16_x,shot_freeze_frame_16_y,shot_freeze_frame_17_x,shot_freeze_frame_17_y,shot_freeze_frame_18_x,shot_freeze_frame_18_y,shot_freeze_frame_19_x,shot_freeze_frame_19_y
0,0,6d37980b-64c4-4bc3-be83-5b7c676fff3d,157,1,2022-11-24 00:02:59.591,2,59,6,England Women's,10180,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,b987eba2-a8bd-4863-b96f-2269e3d3487e,345,1,2022-11-24 00:09:18.826,9,18,19,Germany Women's,10263,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,c876fe4b-7089-42ec-93b7-533c42182ac1,426,1,2022-11-24 00:11:44.696,11,44,22,Germany Women's,10263,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,9b914e4d-6b26-45a9-9c56-4f2926c9ef74,531,1,2022-11-24 00:18:12.880,18,12,33,England Women's,4643,...,108.4,38.9,111.7,45.4,93.9,24.2,113.6,38.4,0.0,0.0
4,4,f4ad7e44-0db5-43ee-9717-0906df3fee2a,536,1,2022-11-24 00:18:36.404,18,36,34,England Women's,10178,...,106.4,44.7,119.1,39.9,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
a = ['Unnamed: 0']
df = df.drop(a, axis =1)
df.head()

,id,index,period,timestamp,minute,second,possession,possession_team_name,player_id,player_name,...,shot_freeze_frame_15_x,shot_freeze_frame_15_y,shot_freeze_frame_16_x,shot_freeze_frame_16_y,shot_freeze_frame_17_x,shot_freeze_frame_17_y,shot_freeze_frame_18_x,shot_freeze_frame_18_y,shot_freeze_frame_19_x,shot_freeze_frame_19_y
0,6d37980b-64c4-4bc3-be83-5b7c676fff3d,157,1,2022-11-24 00:02:59.591,2,59,6,England Women's,10180,Ellen White,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,b987eba2-a8bd-4863-b96f-2269e3d3487e,345,1,2022-11-24 00:09:18.826,9,18,19,Germany Women's,10263,Sara Däbritz,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,c876fe4b-7089-42ec-93b7-533c42182ac1,426,1,2022-11-24 00:11:44.696,11,44,22,Germany Women's,10263,Sara Däbritz,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,9b914e4d-6b26-45a9-9c56-4f2926c9ef74,531,1,2022-11-24 00:18:12.880,18,12,33,England Women's,4643,Georgia Stanway,...,108.4,38.9,111.7,45.4,93.9,24.2,113.6,38.4,0.0,0.0
4,f4ad7e44-0db5-43ee-9717-0906df3fee2a,536,1,2022-11-24 00:18:36.404,18,36,34,England Women's,10178,Lucy Bronze,...,106.4,44.7,119.1,39.9,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
df['location0']= df[['shot_freeze_frame_0_x', 'shot_freeze_frame_0_y']].values.tolist()
df['location1']= df[['shot_freeze_frame_1_x', 'shot_freeze_frame_1_y']].values.tolist()
df['location2']= df[['shot_freeze_frame_2_x', 'shot_freeze_frame_2_y']].values.tolist()
df['location3']= df[['shot_freeze_frame_3_x', 'shot_freeze_frame_3_y']].values.tolist()
df['location4']= df[['shot_freeze_frame_4_x', 'shot_freeze_frame_4_y']].values.tolist()
df['location5']= df[['shot_freeze_frame_5_x', 'shot_freeze_frame_5_y']].values.tolist()
df['location6']= df[['shot_freeze_frame_6_x', 'shot_freeze_frame_6_y']].values.tolist()
df['location7']= df[['shot_freeze_frame_7_x', 'shot_freeze_frame_7_y']].values.tolist()
df['location8']= df[['shot_freeze_frame_8_x', 'shot_freeze_frame_8_y']].values.tolist()
df['location9']= df[['shot_freeze_frame_9_x', 'shot_freeze_frame_9_y']].values.tolist()
df['location10']= df[['shot_freeze_frame_10_x', 'shot_freeze_frame_10_y']].values.tolist()

df['location11']= df[['shot_freeze_frame_11_x', 'shot_freeze_frame_11_y']].values.tolist()
df['location12']= df[['shot_freeze_frame_12_x', 'shot_freeze_frame_12_y']].values.tolist()
df['location13']= df[['shot_freeze_frame_13_x', 'shot_freeze_frame_13_y']].values.tolist()
df['location14']= df[['shot_freeze_frame_14_x', 'shot_freeze_frame_14_y']].values.tolist()
df['location15']= df[['shot_freeze_frame_15_x', 'shot_freeze_frame_15_y']].values.tolist()
df['location16']= df[['shot_freeze_frame_16_x', 'shot_freeze_frame_16_y']].values.tolist()
df['location17']= df[['shot_freeze_frame_17_x', 'shot_freeze_frame_17_y']].values.tolist()
df['location18']= df[['shot_freeze_frame_18_x', 'shot_freeze_frame_18_y']].values.tolist()
df['location19']= df[['shot_freeze_frame_19_x', 'shot_freeze_frame_19_y']].values.tolist()
#df['location20']= df[['shot_freeze_frame_20_x', 'shot_freeze_frame_20_y']].values.tolist()


a = ['shot_freeze_frame_0_x', 'shot_freeze_frame_0_y',
       'shot_freeze_frame_1_x', 'shot_freeze_frame_1_y',
       'shot_freeze_frame_2_x', 'shot_freeze_frame_2_y',
       'shot_freeze_frame_3_x', 'shot_freeze_frame_3_y',
       'shot_freeze_frame_4_x', 'shot_freeze_frame_4_y',
       'shot_freeze_frame_5_x', 'shot_freeze_frame_5_y',
       'shot_freeze_frame_6_x', 'shot_freeze_frame_6_y',
       'shot_freeze_frame_7_x', 'shot_freeze_frame_7_y',
       'shot_freeze_frame_8_x', 'shot_freeze_frame_8_y',
       'shot_freeze_frame_9_x', 'shot_freeze_frame_9_y',
       'shot_freeze_frame_10_x', 'shot_freeze_frame_10_y',
       'shot_freeze_frame_11_x', 'shot_freeze_frame_11_y',
       'shot_freeze_frame_12_x', 'shot_freeze_frame_12_y',
       'shot_freeze_frame_13_x', 'shot_freeze_frame_13_y',
       'shot_freeze_frame_14_x', 'shot_freeze_frame_14_y',
       'shot_freeze_frame_15_x', 'shot_freeze_frame_15_y',
       'shot_freeze_frame_16_x', 'shot_freeze_frame_16_y',
       'shot_freeze_frame_17_x', 'shot_freeze_frame_17_y',
       'shot_freeze_frame_18_x', 'shot_freeze_frame_18_y',
       'shot_freeze_frame_19_x', 'shot_freeze_frame_19_y']

df = df.drop(a, axis = 1)
df['location']= df[['location_x', 'location_y']].values.tolist()

In [15]:
def vectorize(pointa, pointb):
    '''
    Given two points, create a vector from the first to the second
    
    Arguments:
        pointa, pointb - x,y co-ordinates (list)
    
    Returns:
        vector from point a to point b
    '''
    return [pointb[0]-pointa[0], pointb[1]-pointa[1]]


def isInside(point_shot, point_goal1, point_goal2, point_freeze):
    '''
    Given the three vertices of a triangle, this function determines if a fourth
    point lies inside the triangle
    
    Arguments:
        point_shot - shot location x,y (list)
        point_goal1 and point_goal2 - goal edges x,y (list)
        point_freeze - player location x,y(list)
        
    Returns:
        True or False (boolean)
    
    '''
    v2 = vectorize(point_freeze, point_shot)
    v0 = vectorize(point_goal1, point_shot)
    v1 = vectorize(point_goal2, point_shot)

    u = (np.dot(v1, v1)*np.dot(v2, v0)-np.dot(v1, v0)*np.dot(v2, v1)) / \
        (np.dot(v0, v0)*np.dot(v1, v1)-np.dot(v0, v1)*np.dot(v1, v0))
    v = (np.dot(v0, v0)*np.dot(v2, v1)-np.dot(v0, v1)*np.dot(v2, v0)) / \
        (np.dot(v0, v0)*np.dot(v1, v1)-np.dot(v0, v1)*np.dot(v1, v0))

    if u < 0 or v < 0:
        return False
    elif u > 1 or v > 1:
        return False
    elif u+v > 1:
        return False
    else:
        return True

In [16]:
goal_x1y1 = [120, 36]
goal_x2y2 = [120, 44]

a = []
b = []
c = []
d = []
e = []
f = []
g = []
h = []
i1 = []
j = []
k = []
l = []
m = []
n = []
o = []
p = []
q = []
r = []
s = []
t = []
u = []


for i in range(0, df.shape[0]):
    a.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location0'][i]))
    b.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location1'][i]))
    c.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location2'][i]))
    d.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location3'][i]))
    
    e.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location4'][i]))
    f.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location5'][i]))
    g.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location6'][i]))
    h.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location7'][i]))
    
    i1.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location8'][i]))
    j.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location9'][i]))
    k.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location10'][i]))
    l.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location11'][i]))
    
    m.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location12'][i]))
    n.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location13'][i]))
    o.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location14'][i]))
    p.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location15'][i]))
    
    q.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location16'][i]))
    r.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location17'][i]))
    s.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location18'][i]))
    t.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location19'][i]))
    
    #u.append(isInside(goal_x1y1, goal_x2y2, df['location'][i], df['location20'][i]))

In [17]:
df['inside0'] = pd.DataFrame(a)
df['inside1'] = pd.DataFrame(b)
df['inside2'] = pd.DataFrame(c)
df['inside3'] = pd.DataFrame(d)

df['inside4'] = pd.DataFrame(e)
df['inside5'] = pd.DataFrame(f)
df['inside6'] = pd.DataFrame(g)
df['inside7'] = pd.DataFrame(h)

df['inside8'] = pd.DataFrame(i1)
df['inside9'] = pd.DataFrame(j)
df['inside10'] = pd.DataFrame(k)
df['inside11'] = pd.DataFrame(l)

df['inside12'] = pd.DataFrame(m)
df['inside13'] = pd.DataFrame(n)
df['inside14'] = pd.DataFrame(o)
df['inside15'] = pd.DataFrame(p)

df['inside16'] = pd.DataFrame(q)
df['inside17'] = pd.DataFrame(r)
df['inside18'] = pd.DataFrame(s)
df['inside19'] = pd.DataFrame(t)

#df['inside20'] = pd.DataFrame(u)

In [18]:
df['inside0'] = df['inside0'] * 1
df['inside1'] = df['inside1'] * 1
df['inside2'] = df['inside2'] * 1
df['inside3'] = df['inside3'] * 1

df['inside4'] = df['inside4'] * 1
df['inside5'] = df['inside5'] * 1
df['inside6'] = df['inside6'] * 1
df['inside7'] = df['inside7'] * 1

df['inside8'] = df['inside8'] * 1
df['inside9'] = df['inside9'] * 1
df['inside10'] = df['inside10'] * 1
df['inside11'] = df['inside11'] * 1

df['inside12'] = df['inside12'] * 1
df['inside13'] = df['inside13'] * 1
df['inside14'] = df['inside14'] * 1
df['inside15'] = df['inside15'] * 1

df['inside16'] = df['inside16'] * 1
df['inside17'] = df['inside17'] * 1
df['inside18'] = df['inside18'] * 1
df['inside19'] = df['inside19'] * 1

#df['inside20'] = df['inside20'] * 1

In [19]:
df['pack_density'] = (df['inside0'] + df['inside1'] + df['inside2'] + df['inside3'] + 
                    df['inside4'] + df['inside5'] + df['inside6'] + df['inside7'] +
                    df['inside8'] + df['inside9'] + df['inside10'] + df['inside11'] + 
                    df['inside12'] + df['inside13'] + df['inside14'] + df['inside15'] +
                    df['inside16'] + df['inside17'] + df['inside18'] + df['inside19'])

In [20]:
df['pack_density'].value_counts()

1     343
2     274
3     104
4      52
5      36
0      32
6      22
7       6
8       4
10      2
9       1
Name: pack_density, dtype: int64

In [21]:
df.columns

Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'possession',
       'possession_team_name', 'player_id', 'player_name', 'duration',
       'under_pressure', 'play_pattern_name', 'shot_freeze_frame',
       'shot_type_name', 'shot_technique_name', 'shot_outcome_name',
       'shot_body_part_name', 'shot_statsbomb_xg', 'previous_type_name',
       'previous_pass_height_name', 'location_x', 'location_y',
       'shot_end_location_x', 'shot_end_location_y', 'match_id',
       'home_team_home_team_name', 'away_team_away_team_name', 'home_away',
       'location0', 'location1', 'location2', 'location3', 'location4',
       'location5', 'location6', 'location7', 'location8', 'location9',
       'location10', 'location11', 'location12', 'location13', 'location14',
       'location15', 'location16', 'location17', 'location18', 'location19',
       'location', 'inside0', 'inside1', 'inside2', 'inside3', 'inside4',
       'inside5', 'inside6', 'inside7', 'inside8', 'inside9', 'inside10',
       'inside11', 'inside12', 'inside13', 'inside14', 'inside15', 'inside16',
       'inside17', 'inside18', 'inside19', 'pack_density'],
      dtype='object')

In [22]:
s = ['location0', 'location1', 'location2', 'location3', 'location4',
       'location5', 'location6', 'location7', 'location8', 'location9',
       'location10', 'location11', 'location12', 'location13', 'location14',
       'location15', 'location16', 'location17', 'location18', 'location19',
       'location', 'inside0', 'inside1', 'inside2', 'inside3', 'inside4',
       'inside5', 'inside6', 'inside7', 'inside8', 'inside9', 'inside10',
       'inside11', 'inside12', 'inside13', 'inside14', 'inside15', 'inside16',
       'inside17', 'inside18', 'inside19']

df = df.drop(s, axis = 1)
df.head()
print(df.shape)

(876, 30)

In [23]:
#df.to_excel("WWCUP_shots.xlsx")
#df.to_excel("Laligafinal_shots.xlsx")

#df.to_excel("EPL_shots.xlsx")
#df.to_excel("FAWSL_shots.xlsx")
#df.to_excel("FWCUP_shots.xlsx")


#df.to_excel("ISL_shots.xlsx")
#df.to_excel("NWSL_shots.xlsx")
#df.to_excel("UCLfinal_shots.xlsx")

#df.to_excel("UEURO_shots.xlsx")
df.to_excel("UWEURO_shots.xlsx")