In [1]:
import pandas as pd 
import numpy as np

df_wwcup = pd.read_excel("WWCUP_shots.xlsx")
df_wwcup['league_trophy'] = 'WWCUP'
print(df_wwcup.shape)
df_laliga = pd.read_excel("Laligafinal_shots.xlsx")
df_laliga['league_trophy'] = 'Laliga'
print(df_laliga.shape)

df_epl = pd.read_excel("EPL_shots.xlsx")
df_epl['league_trophy'] = 'EPL'
print(df_epl.shape)
df_fawsl = pd.read_excel("FAWSL_shots.xlsx")
df_fawsl['league_trophy'] = 'FAWSL'
print(df_fawsl.shape)
df_fwcup = pd.read_excel("FWCUP_shots.xlsx")
df_fwcup['league_trophy'] = 'FWCUP'
print(df_fwcup.shape)

df_isl = pd.read_excel("ISL_shots.xlsx")
df_isl['league_trophy'] = 'ISL'
print(df_isl.shape)
df_nwsl = pd.read_excel("NWSL_shots.xlsx")
df_nwsl['league_trophy'] = 'NWSL'
print(df_nwsl.shape)
df_ucl = pd.read_excel("UCLfinal_shots.xlsx")
df_ucl['league_trophy'] = 'UCL'
print(df_ucl.shape)


df_ueuro = pd.read_excel("UEURO_shots.xlsx")
df_ueuro['league_trophy'] = 'UEURO'
print(df_ueuro.shape)
df_uweuro = pd.read_excel("UWEURO_shots.xlsx")
df_uweuro['league_trophy'] = 'UWEURO'
print(df_uweuro.shape)


frames = [df_wwcup, df_laliga, df_epl, df_fawsl, df_fwcup, 
         df_isl, df_nwsl, df_ucl, df_ueuro, df_uweuro]

df = pd.concat(frames)

print(df.shape)
print(df.columns)

(1314, 32)
(12840, 32)
(798, 73)
(8321, 32)
(1706, 32)
(3095, 32)
(1041, 32)
(456, 32)
(1289, 32)
(876, 32)
(31736, 73)
Index(['Unnamed: 0', 'id', 'index', 'period', 'timestamp', 'minute', 'second',
       'possession', 'possession_team_name', 'player_id', 'player_name',
       'duration', 'under_pressure', 'play_pattern_name', 'shot_freeze_frame',
       'shot_type_name', 'shot_technique_name', 'shot_outcome_name',
       'shot_body_part_name', 'shot_statsbomb_xg', 'previous_type_name',
       'previous_pass_height_name', 'location_x', 'location_y',
       'shot_end_location_x', 'shot_end_location_y', 'match_id',
       'home_team_home_team_name', 'away_team_away_team_name', 'home_away',
       'pack_density', 'league_trophy', 'location0', 'location1', 'location2',
       'location3', 'location4', 'location5', 'location6', 'location7',
       'location8', 'location9', 'location10', 'location11', 'location12',
       'location13', 'location14', 'location15', 'location16', 'location17',
       'location18', 'location19', 'location', 'inside0', 'inside1', 'inside2',
       'inside3', 'inside4', 'inside5', 'inside6', 'inside7', 'inside8',
       'inside9', 'inside10', 'inside11', 'inside12', 'inside13', 'inside14',
       'inside15', 'inside16', 'inside17', 'inside18', 'inside19'],
      dtype='object')

In [2]:
df['league_trophy'].value_counts()

Laliga    12840
FAWSL      8321
ISL        3095
FWCUP      1706
WWCUP      1314
UEURO      1289
NWSL       1041
UWEURO      876
EPL         798
UCL         456
Name: league_trophy, dtype: int64

In [3]:
import ast

for i in range(0, df.shape[0]-1):
    try:
        df['shot_freeze_frame'].iloc[i] = ast.literal_eval(df['shot_freeze_frame'].iloc[i])
    except:
        None

/Users/aritramajumdar/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

In [4]:
def dict_to_dataframe(a):
    dataframe = df[a].apply(pd.Series)
    dataframe.columns = [str(a) + "_" + str(col) for col in dataframe.columns]
    return dataframe

df_sff = dict_to_dataframe('shot_freeze_frame')
print(df_sff.shape)

(31736, 21)

In [5]:
df_sff.head()

,shot_freeze_frame_0,shot_freeze_frame_1,shot_freeze_frame_2,shot_freeze_frame_3,shot_freeze_frame_4,shot_freeze_frame_5,shot_freeze_frame_6,shot_freeze_frame_7,shot_freeze_frame_8,shot_freeze_frame_9,...,shot_freeze_frame_11,shot_freeze_frame_12,shot_freeze_frame_13,shot_freeze_frame_14,shot_freeze_frame_15,shot_freeze_frame_16,shot_freeze_frame_17,shot_freeze_frame_18,shot_freeze_frame_19,shot_freeze_frame_20
0,"{'location': [116.0, 43.0], 'player': {'id': 2...","{'location': [107.0, 41.1], 'player': {'id': 2...","{'location': [106.7, 28.2], 'player': {'id': 2...","{'location': [94.1, 13.0], 'player': {'id': 25...","{'location': [94.1, 35.6], 'player': {'id': 25...","{'location': [99.6, 51.7], 'player': {'id': 25...","{'location': [104.5, 60.5], 'player': {'id': 2...","{'location': [95.6, 66.6], 'player': {'id': 25...","{'location': [92.9, 57.4], 'player': {'id': 25...","{'location': [84.7, 36.7], 'player': {'id': 49...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"{'location': [102.7, 34.2], 'player': {'id': 2...","{'location': [108.3, 38.0], 'player': {'id': 2...","{'location': [101.7, 26.4], 'player': {'id': 2...","{'location': [98.6, 15.8], 'player': {'id': 25...","{'location': [102.6, 9.4], 'player': {'id': 25...","{'location': [97.4, 28.8], 'player': {'id': 25...","{'location': [97.8, 37.3], 'player': {'id': 50...","{'location': [106.8, 43.8], 'player': {'id': 5...","{'location': [105.0, 29.9], 'player': {'id': 2...","{'location': [107.3, 42.0], 'player': {'id': 2...",...,"{'location': [118.3, 39.9], 'player': {'id': 2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"{'location': [88.5, 44.8], 'player': {'id': 50...","{'location': [97.5, 47.2], 'player': {'id': 25...","{'location': [107.9, 38.2], 'player': {'id': 2...","{'location': [108.8, 39.0], 'player': {'id': 2...","{'location': [118.9, 42.8], 'player': {'id': 2...","{'location': [108.2, 46.4], 'player': {'id': 2...","{'location': [108.3, 49.6], 'player': {'id': 2...","{'location': [102.5, 63.6], 'player': {'id': 2...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"{'location': [118.9, 42.1], 'player': {'id': 2...","{'location': [108.9, 36.7], 'player': {'id': 2...","{'location': [111.2, 34.4], 'player': {'id': 2...","{'location': [107.3, 41.2], 'player': {'id': 2...","{'location': [103.2, 39.8], 'player': {'id': 2...","{'location': [106.9, 44.7], 'player': {'id': 2...","{'location': [100.7, 58.6], 'player': {'id': 4...","{'location': [106.6, 66.1], 'player': {'id': 2...","{'location': [99.7, 78.7], 'player': {'id': 50...","{'location': [107.6, 63.0], 'player': {'id': 2...",...,"{'location': [102.2, 55.9], 'player': {'id': 2...","{'location': [110.0, 36.2], 'player': {'id': 2...","{'location': [95.4, 31.1], 'player': {'id': 25...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"{'location': [113.3, 41.6], 'player': {'id': 2...","{'location': [112.5, 42.3], 'player': {'id': 2...","{'location': [114.1, 46.1], 'player': {'id': 5...","{'location': [106.8, 38.4], 'player': {'id': 2...","{'location': [108.7, 36.1], 'player': {'id': 5...","{'location': [118.1, 79.5], 'player': {'id': 2...","{'location': [113.0, 67.7], 'player': {'id': 2...","{'location': [119.3, 40.7], 'player': {'id': 2...","{'location': [120.0, 43.0], 'player': {'id': 2...","{'location': [110.6, 34.7], 'player': {'id': 2...",...,"{'location': [111.9, 39.8], 'player': {'id': 2...","{'location': [114.7, 42.9], 'player': {'id': 2...","{'location': [120.0, 36.6], 'player': {'id': 2...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
from pandas import isnull
df_sff=df_sff.applymap(lambda x: {'location': [0, 0], 'position': {'name': 'Center Defensive Midfield'}} if isnull(x) else x)

In [7]:
def gk_pos(col):
    pos_x = []
    pos_y = []
    for i in range(0, df.shape[0]):
        try:
            if df_sff[col].values[i]['position']['name'] == 'Goalkeeper':
                x = df_sff[col].values[i]['location'][0]
                y = df_sff[col].values[i]['location'][1]
                pos_x.append(x)
                pos_y.append(y)
            else:
                pos_x.append(0)
                pos_y.append(0)
        except:
            None
    return pos_x, pos_y

In [8]:
a0_x, a0_y = gk_pos('shot_freeze_frame_0')
df_sff['gk_pos_0_x'] = pd.DataFrame(a0_x)
df_sff['gk_pos_0_y'] = pd.DataFrame(a0_y)


a1_x, a1_y = gk_pos('shot_freeze_frame_1')
df_sff['gk_pos_1_x'] = pd.DataFrame(a1_x)
df_sff['gk_pos_1_y'] = pd.DataFrame(a1_y)


a2_x, a2_y = gk_pos('shot_freeze_frame_2')
df_sff['gk_pos_2_x'] = pd.DataFrame(a2_x)
df_sff['gk_pos_2_y'] = pd.DataFrame(a2_y)


a3_x, a3_y = gk_pos('shot_freeze_frame_3')
df_sff['gk_pos_3_x'] = pd.DataFrame(a3_x)
df_sff['gk_pos_3_y'] = pd.DataFrame(a3_y)


a4_x, a4_y = gk_pos('shot_freeze_frame_4')
df_sff['gk_pos_4_x'] = pd.DataFrame(a4_x)
df_sff['gk_pos_4_y'] = pd.DataFrame(a4_y)


a5_x, a5_y = gk_pos('shot_freeze_frame_1')
df_sff['gk_pos_5_x'] = pd.DataFrame(a5_x)
df_sff['gk_pos_5_y'] = pd.DataFrame(a5_y)


a6_x, a6_y = gk_pos('shot_freeze_frame_6')
df_sff['gk_pos_6_x'] = pd.DataFrame(a6_x)
df_sff['gk_pos_6_y'] = pd.DataFrame(a6_y)


a7_x, a7_y = gk_pos('shot_freeze_frame_7')
df_sff['gk_pos_7_x'] = pd.DataFrame(a7_x)
df_sff['gk_pos_7_y'] = pd.DataFrame(a7_y)


a8_x, a8_y = gk_pos('shot_freeze_frame_8')
df_sff['gk_pos_8_x'] = pd.DataFrame(a8_x)
df_sff['gk_pos_8_y'] = pd.DataFrame(a8_y)


a9_x, a9_y = gk_pos('shot_freeze_frame_9')
df_sff['gk_pos_9_x'] = pd.DataFrame(a9_x)
df_sff['gk_pos_9_y'] = pd.DataFrame(a9_y)


a10_x, a10_y = gk_pos('shot_freeze_frame_10')
df_sff['gk_pos_10_x'] = pd.DataFrame(a10_x)
df_sff['gk_pos_10_y'] = pd.DataFrame(a10_y)


a11_x, a11_y = gk_pos('shot_freeze_frame_11')
df_sff['gk_pos_11_x'] = pd.DataFrame(a11_x)
df_sff['gk_pos_11_y'] = pd.DataFrame(a11_y)

a12_x, a12_y = gk_pos('shot_freeze_frame_12')
df_sff['gk_pos_12_x'] = pd.DataFrame(a12_x)
df_sff['gk_pos_12_y'] = pd.DataFrame(a12_y)


a13_x, a13_y = gk_pos('shot_freeze_frame_13')
df_sff['gk_pos_13_x'] = pd.DataFrame(a13_x)
df_sff['gk_pos_13_y'] = pd.DataFrame(a13_y)


a14_x, a14_y = gk_pos('shot_freeze_frame_14')
df_sff['gk_pos_14_x'] = pd.DataFrame(a14_x)
df_sff['gk_pos_14_y'] = pd.DataFrame(a14_y)


a15_x, a15_y = gk_pos('shot_freeze_frame_15')
df_sff['gk_pos_15_x'] = pd.DataFrame(a15_x)
df_sff['gk_pos_15_y'] = pd.DataFrame(a15_y)

a16_x, a16_y = gk_pos('shot_freeze_frame_16')
df_sff['gk_pos_16_x'] = pd.DataFrame(a16_x)
df_sff['gk_pos_16_y'] = pd.DataFrame(a16_y)


a17_x, a17_y = gk_pos('shot_freeze_frame_17')
df_sff['gk_pos_17_x'] = pd.DataFrame(a17_x)
df_sff['gk_pos_17_y'] = pd.DataFrame(a17_y)


a18_x, a18_y = gk_pos('shot_freeze_frame_18')
df_sff['gk_pos_18_x'] = pd.DataFrame(a18_x)
df_sff['gk_pos_18_y'] = pd.DataFrame(a18_y)


a19_x, a19_y = gk_pos('shot_freeze_frame_19')
df_sff['gk_pos_19_x'] = pd.DataFrame(a19_x)
df_sff['gk_pos_19_y'] = pd.DataFrame(a19_y)

a20_x, a20_y = gk_pos('shot_freeze_frame_20')
df_sff['gk_pos_20_x'] = pd.DataFrame(a20_x)
df_sff['gk_pos_20_y'] = pd.DataFrame(a20_y)

In [9]:
df_sff['gk_pos_x'] = (df_sff['gk_pos_0_x'] + df_sff['gk_pos_1_x'] + df_sff['gk_pos_2_x'] + df_sff['gk_pos_3_x'] +
                    df_sff['gk_pos_4_x'] + df_sff['gk_pos_5_x'] + df_sff['gk_pos_6_x'] + df_sff['gk_pos_7_x'] +
                    df_sff['gk_pos_8_x'] + df_sff['gk_pos_9_x'] + df_sff['gk_pos_10_x'] + df_sff['gk_pos_11_x'] +
                    df_sff['gk_pos_12_x'] + df_sff['gk_pos_13_x'] + df_sff['gk_pos_14_x'] + df_sff['gk_pos_16_x'] +
                    df_sff['gk_pos_17_x'] + df_sff['gk_pos_18_x'] + df_sff['gk_pos_19_x'] + df_sff['gk_pos_20_x'])


df_sff['gk_pos_y'] = (df_sff['gk_pos_0_y'] + df_sff['gk_pos_1_y'] + df_sff['gk_pos_2_y'] + df_sff['gk_pos_3_y'] +
                    df_sff['gk_pos_4_y'] + df_sff['gk_pos_5_y'] + df_sff['gk_pos_6_y'] + df_sff['gk_pos_7_y'] +
                    df_sff['gk_pos_8_y'] + df_sff['gk_pos_9_y'] + df_sff['gk_pos_10_y'] + df_sff['gk_pos_11_y'] +
                    df_sff['gk_pos_12_y'] + df_sff['gk_pos_13_y'] + df_sff['gk_pos_14_y'] + df_sff['gk_pos_16_y'] +
                    df_sff['gk_pos_17_y'] + df_sff['gk_pos_18_y'] + df_sff['gk_pos_19_y'] + df_sff['gk_pos_20_y'])

In [10]:
df_sff.head()

,shot_freeze_frame_0,shot_freeze_frame_1,shot_freeze_frame_2,shot_freeze_frame_3,shot_freeze_frame_4,shot_freeze_frame_5,shot_freeze_frame_6,shot_freeze_frame_7,shot_freeze_frame_8,shot_freeze_frame_9,...,gk_pos_17_x,gk_pos_17_y,gk_pos_18_x,gk_pos_18_y,gk_pos_19_x,gk_pos_19_y,gk_pos_20_x,gk_pos_20_y,gk_pos_x,gk_pos_y
0,"{'location': [116.0, 43.0], 'player': {'id': 2...","{'location': [107.0, 41.1], 'player': {'id': 2...","{'location': [106.7, 28.2], 'player': {'id': 2...","{'location': [94.1, 13.0], 'player': {'id': 25...","{'location': [94.1, 35.6], 'player': {'id': 25...","{'location': [99.6, 51.7], 'player': {'id': 25...","{'location': [104.5, 60.5], 'player': {'id': 2...","{'location': [95.6, 66.6], 'player': {'id': 25...","{'location': [92.9, 57.4], 'player': {'id': 25...","{'location': [84.7, 36.7], 'player': {'id': 49...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,116.0,43.0
1,"{'location': [102.7, 34.2], 'player': {'id': 2...","{'location': [108.3, 38.0], 'player': {'id': 2...","{'location': [101.7, 26.4], 'player': {'id': 2...","{'location': [98.6, 15.8], 'player': {'id': 25...","{'location': [102.6, 9.4], 'player': {'id': 25...","{'location': [97.4, 28.8], 'player': {'id': 25...","{'location': [97.8, 37.3], 'player': {'id': 50...","{'location': [106.8, 43.8], 'player': {'id': 5...","{'location': [105.0, 29.9], 'player': {'id': 2...","{'location': [107.3, 42.0], 'player': {'id': 2...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,118.3,39.9
2,"{'location': [88.5, 44.8], 'player': {'id': 50...","{'location': [97.5, 47.2], 'player': {'id': 25...","{'location': [107.9, 38.2], 'player': {'id': 2...","{'location': [108.8, 39.0], 'player': {'id': 2...","{'location': [118.9, 42.8], 'player': {'id': 2...","{'location': [108.2, 46.4], 'player': {'id': 2...","{'location': [108.3, 49.6], 'player': {'id': 2...","{'location': [102.5, 63.6], 'player': {'id': 2...","{'location': [0, 0], 'position': {'name': 'Cen...","{'location': [0, 0], 'position': {'name': 'Cen...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,118.9,42.8
3,"{'location': [118.9, 42.1], 'player': {'id': 2...","{'location': [108.9, 36.7], 'player': {'id': 2...","{'location': [111.2, 34.4], 'player': {'id': 2...","{'location': [107.3, 41.2], 'player': {'id': 2...","{'location': [103.2, 39.8], 'player': {'id': 2...","{'location': [106.9, 44.7], 'player': {'id': 2...","{'location': [100.7, 58.6], 'player': {'id': 4...","{'location': [106.6, 66.1], 'player': {'id': 2...","{'location': [99.7, 78.7], 'player': {'id': 50...","{'location': [107.6, 63.0], 'player': {'id': 2...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,118.9,42.1
4,"{'location': [113.3, 41.6], 'player': {'id': 2...","{'location': [112.5, 42.3], 'player': {'id': 2...","{'location': [114.1, 46.1], 'player': {'id': 5...","{'location': [106.8, 38.4], 'player': {'id': 2...","{'location': [108.7, 36.1], 'player': {'id': 5...","{'location': [118.1, 79.5], 'player': {'id': 2...","{'location': [113.0, 67.7], 'player': {'id': 2...","{'location': [119.3, 40.7], 'player': {'id': 2...","{'location': [120.0, 43.0], 'player': {'id': 2...","{'location': [110.6, 34.7], 'player': {'id': 2...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,119.3,40.7

In [11]:
df_sff = df_sff[['gk_pos_x', 'gk_pos_y']]

In [12]:
df_sff['gk_pos_x'] = df_sff['gk_pos_x'].replace(0.0, 119.1)
df_sff['gk_pos_y'] = df_sff['gk_pos_y'].replace(0.0, 37.8)

In [13]:
df_shots = pd.concat([df, df_sff], axis = 1)

In [14]:
df_shots.columns

Index(['Unnamed: 0', 'id', 'index', 'period', 'timestamp', 'minute', 'second',
       'possession', 'possession_team_name', 'player_id', 'player_name',
       'duration', 'under_pressure', 'play_pattern_name', 'shot_freeze_frame',
       'shot_type_name', 'shot_technique_name', 'shot_outcome_name',
       'shot_body_part_name', 'shot_statsbomb_xg', 'previous_type_name',
       'previous_pass_height_name', 'location_x', 'location_y',
       'shot_end_location_x', 'shot_end_location_y', 'match_id',
       'home_team_home_team_name', 'away_team_away_team_name', 'home_away',
       'pack_density', 'league_trophy', 'location0', 'location1', 'location2',
       'location3', 'location4', 'location5', 'location6', 'location7',
       'location8', 'location9', 'location10', 'location11', 'location12',
       'location13', 'location14', 'location15', 'location16', 'location17',
       'location18', 'location19', 'location', 'inside0', 'inside1', 'inside2',
       'inside3', 'inside4', 'inside5', 'inside6', 'inside7', 'inside8',
       'inside9', 'inside10', 'inside11', 'inside12', 'inside13', 'inside14',
       'inside15', 'inside16', 'inside17', 'inside18', 'inside19', 'gk_pos_x',
       'gk_pos_y'],
      dtype='object')

In [15]:
df_shots['gk_distance'] = np.sqrt(((df_shots['location_x'] - df_shots['gk_pos_x'])**2) + ((df_shots['location_y'] - df_shots['gk_pos_y'])**2))

In [16]:
df_shots['gk_distance'] = df_shots['gk_distance'].round(2)
df_shots.head()

,Unnamed: 0,id,index,period,timestamp,minute,second,possession,possession_team_name,player_id,...,inside13,inside14,inside15,inside16,inside17,inside18,inside19,gk_pos_x,gk_pos_y,gk_distance
0,0,56deeffa-ff55-429e-91df-41f237a3ebac,277,1,2022-11-23 00:04:49.357,4,49,12,Australia Women's,4961,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.0,43.0,12.73
1,1,00d9c066-1078-4e1c-8c7f-2ca299e3a5f0,484,1,2022-11-23 00:10:14.178,10,14,25,Australia Women's,4961,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.3,39.9,11.18
2,2,48706448-928f-4721-96ec-2b813f448937,839,1,2022-11-23 00:18:12.068,18,12,38,Australia Women's,4961,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.9,42.8,11.67
3,3,718f8a06-078c-489e-9423-63d414be5e43,1151,1,2022-11-23 00:24:52.927,24,52,48,Australia Women's,4961,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.9,42.1,13.00
4,4,e1b29724-4861-4d12-9a51-ac6635e97438,1156,1,2022-11-23 00:25:27.514,25,27,49,Australia Women's,4961,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.3,40.7,7.24

In [17]:
df_shots['gk_distance'] = df_shots['gk_distance'].fillna(0)

In [18]:
df_shots['gk_distance']

0      12.73
1      11.18
2      11.67
3      13.00
4       7.24
       ...
871    18.34
872    25.76
873    23.31
874    25.52
875    20.26
Name: gk_distance, Length: 31736, dtype: float64

In [19]:
df_shots['gk_distance'].value_counts()

11.32     41
11.24     40
9.90      30
12.59     29
14.62     29
          ..
145.17     1
145.12     1
124.53     1
135.92     1
34.02      1
Name: gk_distance, Length: 5711, dtype: int64

In [20]:
df_shots.to_excel("shots.xlsx")